# Generated by Django 4.1 on 2023-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
