# Generated by Django 4.1 on 2023-01-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookery", "0002_alter_recipestep_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipestep",
            name="order_num",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
