# Generated by Django 4.1 on 2023-01-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookery", "0003_recipestep_order_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="weight",
        ),
        migrations.CreateModel(
            name="RecipeIngridient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookery.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingridients",
                        to="cookery.recipe",
                    ),
                ),
            ],
        ),
    ]
