# Generated by Django 4.1 on 2023-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
