# Generated by Django 4.1 on 2023-01-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
