# Generated by Django 4.1 on 2023-01-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0002_menuitem_title_alter_menuitem_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtable",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
