# Generated by Django 4.1 on 2023-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_recipe_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="minutes_to_cook",
            field=models.IntegerField(default=30),
        ),
    ]
