# Generated by Django 4.1 on 2023-01-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_recipe_minutes_to_cook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="title",
        ),
    ]
