# Generated by Django 4.1 on 2023-01-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "waiting"),
                    ("2", "cooking"),
                    ("3", "finished"),
                    ("4", "delivered"),
                ],
                default="1",
                max_length=50,
            ),
        ),
    ]
