# Generated by Django 4.1 on 2023-01-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
