# Generated by Django 4.1 on 2023-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "draft"),
                    ("2", "waiting"),
                    ("3", "cooking"),
                    ("4", "finished"),
                    ("5", "delivered"),
                ],
                default="1",
                max_length=50,
            ),
        ),
    ]
