# Generated by Django 4.1 on 2023-01-19 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cookery",
            "0005_menu_dish_is_available_dish_price_menucategory_and_more",
        ),
        ("orders", "0006_alter_orderitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="menu_item",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="dish",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="cookery.dish",
            ),
            preserve_default=False,
        ),
    ]
